hydra:
  job:
    name: default
    chdir: false
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M}
  
# ================================================ #

py_module: autoregressive_policy

model:
  weights: null

  hp:
    add_corr: true
    add_depth: true
    add_lang: true
    add_pixel_loc: true
    add_proprio: true
    attn_dim: 512
    attn_dim_head: 64
    attn_dropout: 0.1
    attn_heads: 8
    depth: 8
    feat_dim: 220 # 72*3 + 4
    im_channels: 64
    point_augment_noise: 0.05
    img_feat_dim: 3
    img_patch_size: 14
    img_size: 224
    lang_dim: 512
    lang_len: 77
    norm_corr: true
    pe_fix: true
    proprio_dim: 3 # 4 # 18
    mvt_cameras: ['top', 'left', 'front']
    stage2_zoom_scale: 4
    stage2_waypoint_label_noise: 0.05
    rotation_aug: #null
      - [-2, -1, 0, -1, -2]
      - [0.1, 0.2, 0.4, 0.2, 0.1]
    use_xformers: true

    gt_hm_sigma: 1.5
    move_pc_in_bound: true
    place_with_mean: false

    amp: True
    bnb: True

    # lr should be thought on per sample basis
    # effective lr is multiplied by bs * num_devices
    lr: 1.25e-5 #1.25e-5 # 1e-4
    warmup_steps: 2000
    optimizer_type: lamb
    lr_cos_dec: true
    add_rgc_loss: true
    transform_augmentation: true
    transform_augmentation_xyz: [0.125, 0.125, 0.125]
    transform_augmentation_rpy: [0.0, 0.0, 45.0]
    lambda_weight_l2: 1e-4 # 1e-6
    num_rotation_classes: 72

    cos_dec_max_step: -1 # will be override during training

    render_with_cpp: true



env:
  tasks: all # stack_cups
  cameras: ["front", "left_shoulder", "right_shoulder", "wrist"]
  scene_bounds: [-0.3, -0.5, 0.6, 0.7, 0.5, 1.6] # [x_min, y_min, z_min, x_max, y_max, z_max] - the metric volume to be voxelized
  image_size: 128
  time_in_state: false
  voxel_size: 100
  episode_length: 25
  rotation_resolution: 5
  origin_style_state: true

train:
  bs: 96 # 48
  demo_folder: ./data/train
  epochs: 100 # 100
  num_gpus: 4
  num_workers: 8 #, need larger value
  num_transitions_per_epoch: 160000
  disp_freq: 100
  cached_dataset_path: null
  save_freq: 10000
  eval_mode: false
  k2k_sample_ratios: 
    place_cups: 1.0
    stack_cups: 1.0
    close_jar: 1.0
    push_buttons: 1.0
    meat_off_grill: 1.0
    stack_blocks: 1.0
    reach_and_drag: 1.0
    slide_block_to_color_target: 1.0
    place_shape_in_shape_sorter: 1.0
    open_drawer: 1.0
    sweep_to_dustpan_of_size: 1.0
    put_groceries_in_cupboard: 1.0
    light_bulb_in: 1.0
    turn_tap: 1.0
    insert_onto_square_peg: 1.0
    put_item_in_drawer: 1.0
    put_money_in_safe: 1.0
    place_wine_at_rack_location: 1.0

eval:
  datafolder: ./data/test
  episode_num: 25
  start_episode: 0
  headless: true
  save_video: false
  device: 0



output_dir: ${hydra:run.dir}
wandb: null
